// SPDX-License-Identifier: BSD-3-Clause
// Copyright (c) 2026 Bryce M. Westheimer. All rights reserved.

/// @file boys_function_float.cpp
/// @brief Float32 (single-precision) Chebyshev Boys function implementation
///
/// Provides boys_chebyshev_float() and boys_chebyshev_array_float() using
/// float32-truncated Chebyshev coefficients derived from the double-precision
/// tables. Uses 30 intervals (T in [0, 30)) with 8 Chebyshev terms per
/// interval, giving relative accuracy < 1e-6 as required for float32.

#include "libaccint/math/boys_function_float.hpp"
#include "libaccint/math/boys_tables.hpp"

#include <cassert>
#include <cmath>

namespace libaccint::math {

// ============================================================================
// Float32 Chebyshev Coefficient Table
// ============================================================================

namespace {

/// @brief Number of intervals for float32 Chebyshev interpolation
constexpr int FLOAT_CHEB_N_INTERVALS = 30;

/// @brief Number of Chebyshev terms per interval (float32)
///
/// 8 terms (degree-7 polynomial) gives relative error < 1e-7 for float32,
/// well within the target accuracy of 1e-6.
constexpr int FLOAT_CHEB_N_TERMS = 8;

/// @brief Number of Boys function orders stored
constexpr int FLOAT_CHEB_N_ORDERS = 31;

/// @brief Internal float Chebyshev coefficient table
///
/// Generated by truncating the double-precision Chebyshev table:
/// - Uses the first 8 of the 12 double-precision coefficients per interval
/// - Covers 30 intervals (T in [0, 30)) matching BOYS_CHEBYSHEV_T_MAX_FLOAT
/// - Stores coefficients for all orders 0..30
struct FloatChebyshevTable {
    float coeffs[FLOAT_CHEB_N_INTERVALS][FLOAT_CHEB_N_ORDERS][FLOAT_CHEB_N_TERMS];
};

/// @brief Build the float coefficient table from double-precision data
///
/// At initialization time, truncate the high-precision double coefficients
/// to float. The truncation error is ~1e-8, well within our target 1e-6.
FloatChebyshevTable build_float_table() {
    FloatChebyshevTable table{};
    for (int i = 0; i < FLOAT_CHEB_N_INTERVALS; ++i) {
        for (int n = 0; n < FLOAT_CHEB_N_ORDERS; ++n) {
            for (int k = 0; k < FLOAT_CHEB_N_TERMS; ++k) {
                table.coeffs[i][n][k] = static_cast<float>(
                    detail::BOYS_CHEBYSHEV_COEFFICIENTS[i][n][k]);
            }
        }
    }
    return table;
}

/// @brief Singleton accessor for the float coefficient table
const FloatChebyshevTable& get_float_table() {
    static const FloatChebyshevTable table = build_float_table();
    return table;
}

/// @brief Evaluate Chebyshev expansion via Clenshaw recurrence (float32)
///
/// Same algorithm as the double-precision version but in float arithmetic.
///
/// @param coeffs Pointer to N Chebyshev coefficients
/// @param N Number of terms
/// @param x Evaluation point in [-1, 1]
/// @return Value of the Chebyshev expansion at x
inline float clenshaw_eval_float(const float* coeffs, int N, float x) {
    float d_next1 = 0.0f;  // d_{k+1}
    float d_next2 = 0.0f;  // d_{k+2}

    for (int j = N - 1; j >= 1; --j) {
        float d_k = 2.0f * x * d_next1 - d_next2 + coeffs[j];
        d_next2 = d_next1;
        d_next1 = d_k;
    }

    return coeffs[0] + x * d_next1 - d_next2;
}

}  // anonymous namespace

// ============================================================================
// Float32 Chebyshev Boys Function Implementation
// ============================================================================

float boys_chebyshev_float(int n, float T) {
    assert(n >= 0 && n <= BOYS_MAX_N_FLOAT &&
           "boys_chebyshev_float: n out of range");
    assert(T >= 0.0f && T < BOYS_CHEBYSHEV_T_MAX_FLOAT &&
           "boys_chebyshev_float: T out of Chebyshev range [0, T_MAX)");

    const auto& table = get_float_table();

    // Determine which interval T falls in (each interval has width 1.0)
    const int interval = static_cast<int>(T);
    const int safe_interval = (interval >= FLOAT_CHEB_N_INTERVALS)
                                  ? FLOAT_CHEB_N_INTERVALS - 1
                                  : interval;

    // Map T to x in [-1, 1] within the interval
    // interval covers [a, b) where a = interval, b = a + 1
    const float a = static_cast<float>(safe_interval);
    const float b = a + 1.0f;
    const float x = (2.0f * T - a - b);  // (b - a) = 1.0, so x = 2T - a - b

    return clenshaw_eval_float(
        table.coeffs[safe_interval][n], FLOAT_CHEB_N_TERMS, x);
}

void boys_chebyshev_array_float(int n_max, float T, float* result) {
    assert(n_max >= 0 && n_max <= BOYS_MAX_N_FLOAT &&
           "boys_chebyshev_array_float: n_max out of range");
    assert(T >= 0.0f && T < BOYS_CHEBYSHEV_T_MAX_FLOAT &&
           "boys_chebyshev_array_float: T out of Chebyshev range [0, T_MAX)");
    assert(result != nullptr &&
           "boys_chebyshev_array_float: result is null");

    const auto& table = get_float_table();

    // Determine which interval T falls in
    const int interval = static_cast<int>(T);
    const int safe_interval = (interval >= FLOAT_CHEB_N_INTERVALS)
                                  ? FLOAT_CHEB_N_INTERVALS - 1
                                  : interval;

    // Map T to x in [-1, 1]
    const float a = static_cast<float>(safe_interval);
    const float b = a + 1.0f;
    const float x = (2.0f * T - a - b);

    // Evaluate each order using Clenshaw recurrence
    for (int n = 0; n <= n_max; ++n) {
        result[n] = clenshaw_eval_float(
            table.coeffs[safe_interval][n], FLOAT_CHEB_N_TERMS, x);
    }
}

}  // namespace libaccint::math
