# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2026 Bryce M. Westheimer. All rights reserved.

"""Type stubs for the libaccint package."""

from typing import List, Optional, Sequence, Union

import numpy as np
from numpy.typing import NDArray

# ---------------------------------------------------------------------------
# Version info
# ---------------------------------------------------------------------------
__version__: str
__author__: str

# ---------------------------------------------------------------------------
# Core types (from C++ extension)
# ---------------------------------------------------------------------------
Real = float
Index = int
Size = int

class AngularMomentum: ...
class DerivativeOrder: ...

class Point3D:
    x: float
    y: float
    z: float
    def __init__(self, x: float = ..., y: float = ..., z: float = ...) -> None: ...
    def __getitem__(self, index: int) -> float: ...
    def __setitem__(self, index: int, value: float) -> None: ...
    def to_numpy(self) -> NDArray[np.float64]: ...
    def distance_squared(self, other: "Point3D") -> float: ...

def n_cartesian(l: int) -> int: ...
def n_spherical(l: int) -> int: ...

# ---------------------------------------------------------------------------
# Basis
# ---------------------------------------------------------------------------
class Shell: ...

class ShellSet: ...

class BasisSet:
    def n_basis_functions(self) -> int: ...
    def n_shells(self) -> int: ...
    def shell_set_pairs(self) -> List[ShellSetPair]: ...
    def shell_set_quartets(self) -> List[ShellSetQuartet]: ...

class Atom:
    def __init__(self, atomic_number: int, position: List[float]) -> None: ...
    @property
    def atomic_number(self) -> int: ...
    @property
    def position(self) -> Point3D: ...

def create_builtin_basis(name: str, atoms: List[Atom]) -> BasisSet: ...

# ---------------------------------------------------------------------------
# Operators
# ---------------------------------------------------------------------------
class OperatorKind: ...

class Operator:
    @staticmethod
    def coulomb() -> "Operator": ...
    @staticmethod
    def overlap() -> "Operator": ...
    @staticmethod
    def kinetic() -> "Operator": ...
    @staticmethod
    def nuclear(params: "PointChargeParams") -> "Operator": ...

class PointChargeParams: ...
class RangeSeparatedParams: ...
class OriginParams: ...
class DistributedMultipoleParams: ...
class ProjectionOperatorParams: ...
class OneElectronOperator: ...

def is_one_electron(op: Operator) -> bool: ...
def is_two_electron(op: Operator) -> bool: ...
def is_multi_component(op: Operator) -> bool: ...
def is_anti_hermitian(op: Operator) -> bool: ...
def is_property_integral(op: Operator) -> bool: ...
def component_count(op: Operator) -> int: ...

# ---------------------------------------------------------------------------
# Buffers
# ---------------------------------------------------------------------------
class ShellPairMeta:
    offset: int
    fi: int
    fj: int
    na: int
    nb: int

class ShellQuartetMeta:
    offset: int
    fi: int
    fj: int
    fk: int
    fl: int
    na: int
    nb: int
    nc: int
    nd: int

class OneElectronBuffer:
    def to_numpy(self) -> NDArray[np.float64]: ...
    def n_shell_pairs(self) -> int: ...
    def pair_meta(self, index: int) -> ShellPairMeta: ...

class TwoElectronBuffer:
    def to_numpy(self) -> NDArray[np.float64]: ...
    def n_shell_quartets(self) -> int: ...
    def quartet_meta(self, index: int) -> ShellQuartetMeta: ...

# ---------------------------------------------------------------------------
# Backend
# ---------------------------------------------------------------------------
class BackendType: ...
class BackendHint: ...

def is_backend_available(backend: BackendType) -> bool: ...
def backend_name(backend: BackendType) -> str: ...

# ---------------------------------------------------------------------------
# Engine
# ---------------------------------------------------------------------------
class DispatchConfig:
    min_gpu_batch_size: int
    min_gpu_primitives: int
    high_am_threshold: int
    min_gpu_shells: int
    enable_auto_tuning: bool
    auto_tune_min_batch: int
    n_gpu_slots: int
    def __init__(self) -> None: ...

class Engine:
    def __init__(self, basis: BasisSet, config: Optional[DispatchConfig] = ...) -> None: ...
    def basis(self) -> BasisSet: ...
    def max_angular_momentum(self) -> int: ...
    def gpu_available(self) -> bool: ...
    def set_dispatch_config(self, config: DispatchConfig) -> None: ...
    # Unified compute() — main entry point, dispatches by argument type
    def compute(self, op: Operator, work_unit: "ShellSetPair", hint: BackendHint = ...) -> "IntegralBuffer": ...
    def compute(self, op: Operator, work_unit: "ShellSetQuartet", hint: BackendHint = ...) -> "IntegralBuffer": ...
    def compute(self, op: Operator, work_unit: "ShellSetQuartet", consumer: "FockBuilder", hint: BackendHint = ...) -> None: ...
    def compute(self, op: Operator, consumer: "FockBuilder", hint: BackendHint = ...) -> None: ...
    # Full matrix convenience methods
    def compute_overlap_matrix(self, hint: Optional[BackendHint] = ...) -> NDArray[np.float64]: ...
    def compute_kinetic_matrix(self, hint: Optional[BackendHint] = ...) -> NDArray[np.float64]: ...
    def compute_nuclear_matrix(self, atoms: List[Atom], hint: Optional[BackendHint] = ...) -> NDArray[np.float64]: ...
    def compute_core_hamiltonian(self, atoms: List[Atom], hint: Optional[BackendHint] = ...) -> NDArray[np.float64]: ...
    def compute_eri_tensor(self, op: Optional[Operator] = ..., hint: Optional[BackendHint] = ...) -> NDArray[np.float64]: ...
    def compute_eri_block(self, op: Operator, quartet: "ShellSetQuartet", hint: Optional[BackendHint] = ...) -> NDArray[np.float64]: ...
    # Named aliases for compute() overloads
    def compute_and_consume(self, op: Operator, consumer: "FockBuilder", hint: Optional[BackendHint] = ...) -> None: ...
    def compute_batch(self, op: Operator, quartet: "ShellSetQuartet", hint: BackendHint = ...) -> TwoElectronBuffer: ...
    def compute_quartet(self, op: Operator, quartet: "ShellSetQuartet", hint: BackendHint = ...) -> TwoElectronBuffer: ...
    def compute_pair(self, op: Operator, pair: "ShellSetPair", hint: BackendHint = ...) -> OneElectronBuffer: ...
    def compute_pair_matrix(self, op: Operator, pair: "ShellSetPair", hint: BackendHint = ...) -> NDArray[np.float64]: ...
    def compute_quartet_and_consume(self, op: Operator, quartet: "ShellSetQuartet", consumer: "FockBuilder", hint: BackendHint = ...) -> None: ...
    def compute_quartets_and_consume(self, op: Operator, quartets: List["ShellSetQuartet"], consumer: "FockBuilder", hint: BackendHint = ...) -> None: ...
    def compute_batch_parallel(self, op: Operator, quartets: List["ShellSetQuartet"], n_threads: int = ..., hint: BackendHint = ...) -> List[TwoElectronBuffer]: ...
    def compute_batch_screened(self, op: Operator, screening: "ScreeningOptions", hint: BackendHint = ...) -> List[TwoElectronBuffer]: ...

# ---------------------------------------------------------------------------
# Consumers
# ---------------------------------------------------------------------------
class FockThreadingStrategy: ...

class FockBuilder:
    def __init__(self, nbf: int) -> None: ...
    def set_density(self, density: NDArray[np.float64]) -> None: ...
    def get_coulomb_matrix(self) -> NDArray[np.float64]: ...
    def get_exchange_matrix(self) -> NDArray[np.float64]: ...
    def get_fock_matrix(self, H_core: NDArray[np.float64], exchange_fraction: float = ...) -> NDArray[np.float64]: ...
    def reset(self) -> None: ...
    def nbf(self) -> int: ...
    def set_threading_strategy(self, strategy: FockThreadingStrategy) -> None: ...
    def threading_strategy(self) -> FockThreadingStrategy: ...
    def prepare_parallel(self, n_threads: int = ...) -> None: ...
    def finalize_parallel(self) -> None: ...

# ---------------------------------------------------------------------------
# Screening
# ---------------------------------------------------------------------------
class ScreeningPreset: ...
class ScreeningOptions: ...
class ScreeningStatistics: ...
class SchwarzBounds: ...

# ---------------------------------------------------------------------------
# Convenience API (from _core)
# ---------------------------------------------------------------------------
def atoms_from_xyz(xyz_string: str) -> List[Atom]: ...
def quick_overlap(basis_name: str, atoms: List[Atom]) -> NDArray[np.float64]: ...
def quick_kinetic(basis_name: str, atoms: List[Atom]) -> NDArray[np.float64]: ...
def quick_nuclear(basis_name: str, atoms: List[Atom]) -> NDArray[np.float64]: ...
def quick_core_hamiltonian(basis_name: str, atoms: List[Atom]) -> NDArray[np.float64]: ...
def quick_fock_build(basis_name: str, atoms: List[Atom], density: NDArray[np.float64]) -> NDArray[np.float64]: ...

# ---------------------------------------------------------------------------
# Advanced types
# ---------------------------------------------------------------------------
class ThreadConfig: ...
class ShellSetKey: ...
class ShellSetPair: ...
class ShellSetQuartet: ...
class PrimitivePairData: ...
class IntegralBuffer: ...
class CpuEngine: ...
class DeviceInfo: ...
class StreamHandle: ...
class BackendError(Exception): ...

# CUDA-conditional types (None when CUDA is not available)
CudaEngine: Optional[type]
GpuFockBuilder: Optional[type]

# ---------------------------------------------------------------------------
# Utility functions
# ---------------------------------------------------------------------------
def version() -> str: ...
def has_cuda_backend() -> bool: ...
def has_openmp() -> bool: ...
def get_device_info(device_id: int = ...) -> Optional[DeviceInfo]: ...
def get_device_count() -> int: ...

# ---------------------------------------------------------------------------
# Convenience API (Python wrappers)
# ---------------------------------------------------------------------------
def basis_set(name: str, atoms: List[Atom]) -> BasisSet: ...
def compute_overlap(basis_or_engine: Union[BasisSet, Engine]) -> NDArray[np.float64]: ...
def compute_kinetic(basis_or_engine: Union[BasisSet, Engine]) -> NDArray[np.float64]: ...
def compute_nuclear(basis_or_engine: Union[BasisSet, Engine], atoms: List[Atom]) -> NDArray[np.float64]: ...
def compute_core_hamiltonian(basis_or_engine: Union[BasisSet, Engine], atoms: List[Atom]) -> NDArray[np.float64]: ...
def build_fock(
    engine: Engine,
    density: NDArray[np.float64],
    core_hamiltonian: Optional[NDArray[np.float64]] = ...,
    exchange_fraction: float = ...,
) -> NDArray[np.float64]: ...
def compute_eri_tensor(engine: Engine, op: Optional[Operator] = ...) -> NDArray[np.float64]: ...
def compute_eri_block(engine: Engine, quartet: ShellSetQuartet, op: Optional[Operator] = ...) -> NDArray[np.float64]: ...
