// SPDX-License-Identifier: BSD-3-Clause
// Copyright (c) 2026 Bryce M. Westheimer. All rights reserved.

#pragma once

/// @file generated_kernel_registry_cuda.hpp
/// @brief Registry and dispatch for code-generated CUDA kernels
///
/// Provides launch functions that accept ShellSetPairDeviceData and dispatch
/// to the appropriate AM-specialized generated kernel.

#include <libaccint/config.hpp>
#include <libaccint/config/max_am.hpp>
#include <libaccint/kernels/optimal_dispatch_table.hpp>

#if LIBACCINT_USE_CUDA

#include <libaccint/basis/device_data.hpp>
#include <libaccint/operators/device_operator_data.hpp>
#include <cuda_runtime.h>

// Forward-declare BatchConfig so this header doesn't need the full
// device_resource_tracker.hpp.
namespace libaccint::device { struct BatchConfig; }

namespace libaccint::kernels::cuda::generated {

/// Maximum angular momentum supported by generated CUDA kernels
/// Derived from LIBACCINT_MAX_AM (set by CMake or defaulting to 4).
/// Currently generated kernels cover AM 0–4 (S through G).
constexpr int GENERATED_TABLE_MAX_AM = 4;
constexpr int GENERATED_MAX_AM =
    (LIBACCINT_MAX_AM < GENERATED_TABLE_MAX_AM) ? LIBACCINT_MAX_AM : GENERATED_TABLE_MAX_AM;

/// Number of K-range variants for dispatch
constexpr int NUM_K_RANGES = static_cast<int>(kernels::kNumContractionRanges);

/// Number of GPU execution strategies
constexpr int NUM_GPU_STRATEGIES = 3;

// Forward declaration — the full class is auto-generated by the codegen system
// (see codegen/libaccint_codegen/templates/cuda/registry.cu.j2)
class KernelRegistry;

// ============================================================================
// Availability queries
// ============================================================================

/// @brief Check if a generated overlap kernel exists for (la, lb)
[[nodiscard]] bool has_generated_overlap(int la, int lb) noexcept;

/// @brief Check if a generated kinetic kernel exists for (la, lb)
[[nodiscard]] bool has_generated_kinetic(int la, int lb) noexcept;

/// @brief Check if a generated nuclear kernel exists for (la, lb)
[[nodiscard]] bool has_generated_nuclear(int la, int lb) noexcept;

/// @brief Check if a generated ERI kernel exists for (la, lb, lc, ld)
[[nodiscard]] bool has_generated_eri(int la, int lb, int lc, int ld) noexcept;

// ============================================================================
// Launch functions (accept ShellSetPairDeviceData / ShellSetQuartetDeviceData)
// ============================================================================

/// @brief Launch a generated overlap kernel for the given shell pair
///
/// @param pair Device data for bra and ket ShellSets (SoA layout)
/// @param d_output Device buffer for output [n_pairs * n_cart_a * n_cart_b]
/// @param stream CUDA stream for kernel launch
void launch_generated_overlap(
    const basis::ShellSetPairDeviceData& pair,
    double* d_output,
    cudaStream_t stream = nullptr);

/// @brief Launch a generated kinetic kernel for the given shell pair
void launch_generated_kinetic(
    const basis::ShellSetPairDeviceData& pair,
    double* d_output,
    cudaStream_t stream = nullptr);

/// @brief Launch a generated nuclear attraction kernel for the given shell pair
void launch_generated_nuclear(
    const basis::ShellSetPairDeviceData& pair,
    const operators::DevicePointChargeData& charges,
    const double* d_boys_coeffs,
    double* d_output,
    cudaStream_t stream = nullptr);

/// @brief Launch a generated ERI kernel for the given shell quartet
void launch_generated_eri(
    const basis::ShellSetQuartetDeviceData& quartet,
    const double* d_boys_coeffs,
    double* d_output,
    cudaStream_t stream = nullptr);

/// @brief Launch a generated ERI kernel with SoA output layout
///
/// SoA layout: d_output[component * n_quartets + quartet_id]
/// Provides coalesced writes for medium/high AM quartets.
/// Only available for AM quartets with total_am >= 3.
void launch_generated_eri_soa(
    const basis::ShellSetQuartetDeviceData& quartet,
    const double* d_boys_coeffs,
    double* d_output,
    cudaStream_t stream = nullptr);

/// @brief Check if SoA output is available for given AM quartet
[[nodiscard]] bool has_generated_eri_soa(int la, int lb, int lc, int ld) noexcept;

/// @brief Launch a cooperative (block-per-quartet) ERI kernel for high AM
///
/// Uses 1 block per shell quartet with threads cooperatively processing
/// the primitive contraction loop. Preferred for total_am >= 5 where
/// per-thread state causes excessive register spilling.
///
/// Grid: n_quartets blocks (one per quartet)
/// Shared memory: N_OUT * sizeof(double) for accumulator
void launch_generated_eri_cooperative(
    const basis::ShellSetQuartetDeviceData& quartet,
    const double* d_boys_coeffs,
    double* d_output,
    cudaStream_t stream = nullptr);

/// @brief Check if a cooperative ERI kernel exists for (la, lb, lc, ld)
[[nodiscard]] bool has_generated_eri_cooperative(int la, int lb, int lc, int ld) noexcept;

// ============================================================================
// K-range-aware availability queries
// ============================================================================

/// @brief Check if a K-range-aware overlap kernel exists
/// @param la Angular momentum of bra shell (0-4)
/// @param lb Angular momentum of ket shell (0-4)
/// @param k  Contraction-degree range
[[nodiscard]] bool has_generated_overlap_k_aware(
    int la, int lb, kernels::ContractionRange k) noexcept;

/// @brief Check if a K-range-aware kinetic kernel exists
[[nodiscard]] bool has_generated_kinetic_k_aware(
    int la, int lb, kernels::ContractionRange k) noexcept;

/// @brief Check if a K-range-aware nuclear kernel exists
[[nodiscard]] bool has_generated_nuclear_k_aware(
    int la, int lb, kernels::ContractionRange k) noexcept;

/// @brief Check if a K-range-aware ERI kernel exists for given strategy
[[nodiscard]] bool has_generated_eri_k_aware(
    int la, int lb, int lc, int ld,
    kernels::ContractionRange k,
    kernels::GpuExecutionStrategy strategy =
        kernels::GpuExecutionStrategy::ThreadPerQuartet) noexcept;

// ============================================================================
// K-range-aware launch functions
// ============================================================================

/// @brief Launch a K-range-aware generated overlap kernel
///
/// @param pair     Device data for bra/ket shells (SoA layout)
/// @param d_output Device buffer for output [n_pairs * n_cart_a * n_cart_b]
/// @param k        Contraction-degree range for dispatch
/// @param stream   CUDA stream for kernel launch
void launch_generated_overlap_k_aware(
    const basis::ShellSetPairDeviceData& pair,
    double* d_output,
    kernels::ContractionRange k,
    cudaStream_t stream = nullptr,
    const device::BatchConfig* batch_cfg = nullptr);

/// @brief Launch a K-range-aware generated kinetic kernel
void launch_generated_kinetic_k_aware(
    const basis::ShellSetPairDeviceData& pair,
    double* d_output,
    kernels::ContractionRange k,
    cudaStream_t stream = nullptr,
    const device::BatchConfig* batch_cfg = nullptr);

/// @brief Launch a K-range-aware generated nuclear attraction kernel
void launch_generated_nuclear_k_aware(
    const basis::ShellSetPairDeviceData& pair,
    const operators::DevicePointChargeData& charges,
    const double* d_boys_coeffs,
    double* d_output,
    kernels::ContractionRange k,
    cudaStream_t stream = nullptr,
    const device::BatchConfig* batch_cfg = nullptr);

/// @brief Launch a K-range-aware generated ERI kernel
///
/// Selects the best available kernel for the given AM quartet, contraction
/// range, and execution strategy.  If no K-specific kernel exists for the
/// requested range, falls back to the default (K-unaware) kernel.
///
/// @param quartet     Device data for 4-center quartet (SoA layout)
/// @param d_boys_coeffs Boys function Chebyshev coefficients
/// @param d_output    Device buffer for output integrals
/// @param k           Contraction-degree range
/// @param strategy    GPU execution strategy (tpq/wpq/bpq)
/// @param stream      CUDA stream for kernel launch
void launch_generated_eri_k_aware(
    const basis::ShellSetQuartetDeviceData& quartet,
    const double* d_boys_coeffs,
    double* d_output,
    kernels::ContractionRange k,
    kernels::GpuExecutionStrategy strategy =
        kernels::GpuExecutionStrategy::ThreadPerQuartet,
    cudaStream_t stream = nullptr,
    const device::BatchConfig* batch_cfg = nullptr);

}  // namespace libaccint::kernels::cuda::generated

#endif  // LIBACCINT_USE_CUDA
